### ISSUE TITLE
identify missing pies

### ISSUE THREAD

**Issue by AddressXception** [PizzaDAO/pizza-oven-py#141]
in some cases requests to render a pie do not even make it to the chainlink node. a request exists on the blockchain but it has not been picked up for whatever reason. This ticket is to implement a feature that can read the oracle node contract for requests that have not been completed or fulfilled and return all of the data that is necessary to generate a render task to complete the request.

this ticket ends at posting the blockchain metadata to ipfs and completing the render task. it probably should not automatically post back to chainlink (since the job doesn't exist in the first place) - but that depends on the implementation.

- add the chainlink oracle address to the .env vars
- add the chainlink order api client address
- read the private contract data in the `commitments` mapping or wherever to determine which requests are still outstanding
- run them

## research considerations
the chainlink node contract sets an expiration time on the incoming request which may make it impossible for the request to be fulfilled. therefore we may have to cancel the request and request another one on the users' behalf. the default timeout is set to 5 minutes which is incredibly short. it is possible that the contract may need to be redeployed.

its possible some changes to the deployed contracts will be required in order to complete this ticket.

**Comment by snackman** [comment]
Tracked here: https://docs.google.com/spreadsheets/d/1mq4WcgeT5IdU2f1WKHrjEgwwsJVfX8-BSfslT0AWIWM/edit#gid=0
